"""empty message

Revision ID: d127f03b3f6f
Revises: 
Create Date: 2019-03-27 19:45:16.163562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd127f03b3f6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('division',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('torneo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('sede', sa.String(length=50), nullable=True),
    sa.Column('id_division', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_division'], ['division.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jornada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torneo', sa.Integer(), nullable=True),
    sa.Column('fecha_init', sa.Date(), nullable=True),
    sa.Column('fecha_end', sa.Date(), nullable=True),
    sa.Column('actual', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['torneo'], ['torneo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hquiniela',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_jornada', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_jornada'], ['jornada.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada', sa.Integer(), nullable=True),
    sa.Column('idEquipoLocal', sa.Integer(), nullable=True),
    sa.Column('idEquipoVisit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idEquipoLocal'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['idEquipoVisit'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['jornada'], ['jornada.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiniela_det',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_quiniela', sa.Integer(), nullable=True),
    sa.Column('id_partido', sa.Integer(), nullable=True),
    sa.Column('reslocal', sa.Integer(), nullable=True),
    sa.Column('resvisit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_partido'], ['partidos.id'], ),
    sa.ForeignKeyConstraint(['id_quiniela'], ['hquiniela.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiniela_det')
    op.drop_table('partidos')
    op.drop_table('hquiniela')
    op.drop_table('jornada')
    op.drop_table('equipos')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('torneo')
    op.drop_table('division')
    # ### end Alembic commands ###
